# serverless.yml
service: apollo-lambda
plugins:
  - serverless-plugin-typescript
  #- serverless-dotenv-plugin
#package:
  #exclude:
    #- node_modules/**
provider:
  name: aws
  runtime: nodejs14.x
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    # hanlder needs js file, so provide the bbuild version of handler
    handler: ./src/index.graphqlHandler
    vpc:
      securityGroupIds:
        ${SecurityGroupIds}
      subnetIds:
        ${SubnetIds}
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true

