"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SquashInputType = exports.SquashType = exports.PotentialMatchUserInputType = exports.userExistT = exports.LikedByUserInputType = exports.LikedByUserType = exports.PotentialMatchUserType = exports.ageRange = exports.ImageData = exports.DataType = exports.SquashNodeType = exports.DeletedType = exports.MessageType = exports.LocationType = void 0;
exports.LocationType = "\n    city: String!,\n    state: String!,\n    country: String!\n";
exports.MessageType = "\n _id: ID!,\n sender: String!,\n receiver: String!,\n text: String!\n createdAt: String\n";
exports.DeletedType = "\n isDeleted: Boolean,\n deletedAt: String,\n";
exports.SquashNodeType = "\n    sport: String!,\n    game_level: String!,\n";
exports.DataType = "\n    img_idx: Int!,\n    imageURL: String!,\n    filePath: String!\n";
exports.ImageData = "\n    img_idx: Int!,\n    file: FileUpload!\n";
exports.ageRange = "\n    minAge: Int!,\n    maxAge: Int!\n";
exports.PotentialMatchUserType = "\n    _id: ID!\n    first_name: String!\n    age: Int!\n    gender: String!\n    sports: [SquashNode!]!\n    description: String\n    location: LocationType!\n    image_set: [Data!]!\n";
exports.LikedByUserType = "\n    _id: ID!\n    first_name: String!\n    age: Int!\n    gender: String!\n    sports: [SquashNode!]!\n    description: String\n    location: LocationType!\n    image_set: [Data!]!\n";
exports.LikedByUserInputType = "\n    _id: ID!\n    first_name: String!\n    age: Int!\n    gender: String!\n    sports: [SquashNodeInput!]!\n    description: String\n    image_set: [DataInput!]!\n    location: LocationInput!\n";
exports.userExistT = "\n    isPhoneExist: Boolean!\n    isDeleted: Boolean!\n";
exports.PotentialMatchUserInputType = "\n    _id: ID!\n    first_name: String!\n    age: Int!\n    gender: String!\n    sports: [SquashNodeInput!]!\n    description: String\n    image_set: [DataInput!]!\n    location: LocationInput!\n";
exports.SquashType = "\n    first_name: String!\n    last_name: String!\n    _id: ID!\n    age: Int!\n    gender: String!\n    sports: [SquashNode!]!\n    location: Location!\n    description: String\n    image_set: [Data!]!\n    matches : [PotentialMatch!]\n    blocked_me : [PotentialMatch!]\n    i_blocked : [PotentialMatch!]\n    likes : [String!]\n    swipesPerDay: Int!\n    sportChangesPerDay: Int!\n    visableLikePerDay: Int!\n    dislikes : [String!]\n    likedByUSers: [LikedByUser!]\n    deleted: DeletedT\n    phoneNumber: String\n    email: String\n  ";
exports.SquashInputType = "\n    first_name: String!\n    last_name: String!\n    _id: ID!\n    age: Int!\n    gender: String!\n    sports: [SquashNodeInput!]!\n    location: LocationInput!\n    description: String\n    image_set: [DataInput!]!\n    deleted: DeletedInput\n    matches : [PotentialMatchInput!]\n    blocked_me : [PotentialMatchInput!]\n    i_blocked : [PotentialMatchInput!]\n    likes : [String!]\n    dislikes : [String!]\n    swipesPerDay: Int!\n    sportChangesPerDay: Int!\n    visableLikePerDay: Int!\n    likedByUSers: [LikedByUserInput!]\n    phoneNumber: String\n    email: String\n  ";
