export const SWIPIES_PER_DAY_LIMIT = 10
export const LIKES_PER_DAY_LIMIT = 3
export const SPORT_CHANGES_PER_DAY = 2
export const dest_gcs_images = "all_images"
export const POST_CHANNEL = 'MESSAGE_CHANNEL'
export const GENDERS = ["male", "female"]
export const LEVELS = ['0', '1', '2']
export const MAX_SPORTS_LIMIT = 5
// chat time currently at 2 days
//export const CHAT_TIMER = 1.728e+8
// chat time currently at 14 days
export const CHAT_TIMER = 1.21e+9
export const LOCATIONS = [
  { city: "amherst", state: "MA", country: "US" },
  { city: "attleboro", state: "MA", country: "US" },
  { city: "auburn", state: "MA", country: "US" },
  { city: "babson park", state: "MA", country: "US" },
  { city: "belmont", state: "MA", country: "US" },
  { city: "beverly", state: "MA", country: "US" },
  { city: "boston", state: "MA", country: "US" },
  { city: "charlestown", state: "MA", country: "US" },
  { city: "concord", state: "MA", country: "US" },
  { city: "deerfield", state: "MA", country: "US" },
  { city: "brookline", state: "MA", country: "US" },
  { city: "cambridge", state: "MA", country: "US" },
  { city: "cohasset", state: "MA", country: "US" },
  { city: "dover", state: "MA", country: "US" },
  { city: "natick", state: "MA", country: "US" },
  { city: "wellesley", state: "MA", country: "US" },
  { city: "dedham", state: "MA", country: "US" },
  { city: "north andover", state: "MA", country: "US" },
  { city: "sudbury", state: "MA", country: "US" },
  { city: "newton center", state: "MA", country: "US" },
  { city: "milton", state: "MA", country: "US" },
  { city: "lexington", state: "MA", country: "US" },
  { city: "south hadley", state: "MA", country: "US" },
  { city: "west newton", state: "MA", country: "US" },
  { city: "groton", state: "MA", country: "US" },
  { city: "allston", state: "MA", country: "US" },
  { city: "haverhill", state: "MA", country: "US" },
  { city: "holyoke", state: "MA", country: "US" },
  { city: "gloucester", state: "MA", country: "US" },
  { city: "worcester", state: "MA", country: "US" },
  { city: "marblehead", state: "MA", country: "US" },
  { city: "north adams", state: "MA", country: "US" },
  { city: "south hamilton", state: "MA", country: "US" },
  { city: "nantucket", state: "MA", country: "US" },
  { city: "newton", state: "MA", country: "US" },
  { city: "needham", state: "MA", country: "US" },
  { city: "great barrington", state: "MA", country: "US" },
  { city: "northampton", state: "MA", country: "US" },
  { city: "springfield", state: "MA", country: "US" },
  { city: "ipswich", state: "MA", country: "US" },
  { city: "weston", state: "MA", country: "US" },
  { city: "williamstown", state: "MA", country: "US" },
  { city: "easthampton", state: "MA", country: "US" },
  { city: "waltham", state: "MA", country: "US" },
  { city: "newton centre", state: "MA", country: "US" },
  { city: "eastham", state: "MA", country: "US" },
  { city: "new bedford", state: "MA", country: "US" },
  { city: "lowell", state: "MA", country: "US" },
  { city: "dorchester", state: "MA", country: "US" },
  { city: "westfield", state: "MA", country: "US" },
];
export const CITIES = [
  "amherst",
  "attleboro",
  "auburn",
  "babson park",
  "belmont",
  "beverly",
  "boston",
  "charlestown",
  "concord",
  "deerfield",
  "brookline",
  "cambridge",
  "cohasset",
  "dover",
  "natick",
  "wellesley",
  "dedham",
  "north andover",
  "sudbury",
  "newton center",
  "milton",
  "lexington",
  "south hadley",
  "west newton",
  "groton",
  "allston",
  "haverhill",
  "holyoke",
  "gloucester",
  "worcester",
  "marblehead",
  "north adams",
  "south hamilton",
  "nantucket",
  "newton",
  "needham",
  "great barrington",
  "northampton",
  "springfield",
  "ipswich",
  "weston",
  "williamstown",
  "easthampton",
  "waltham",
  "newton centre",
  "eastham",
  "new bedford",
  "lowell",
  "dorchester",
  "westfield",
];

export const STATES = [
  "MA"
];
export const COUNTRY = ["US"];
export const SPORTS = [
  "squash",
]
